version: '3.8'

services:
  cctv-streaming:
    build: .
    image: cctv-streaming:latest
    container_name: cctv-streaming
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config:ro
      - cctv-logs:/var/log/cctv-streaming
      - cctv-data:/var/lib/cctv-streaming
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

volumes:
  cctv-logs:
    driver: local
  cctv-data:
    driver: local 